### PR TITLE
pulseeffects: Update to version 4.8.4 and add RNNoise module support

### PR DESCRIPTION
**Pull request by RafaelKr**
this PR updates Pulseeffects to version 4.8.4

This also adds the xiph/rnnoise module to get the new Noise Reduction feature, which is awesome! Works even better than WebRTC.

~~*Draft until I got a response from @wwmm regarding if there should be more dependency updates in issue https://github.com/wwmm/pulseeffects/issues/868#issuecomment-756439655*~~

### CODE REVIEW

**Comment by AsavarTzeth** [comment]
Looks good! Much appreciated!

**Comment by RafaelKr** [comment]
Great! Thanks for merging so fast. How long does it usually take until it's available via Flathub?

**Comment by AsavarTzeth** [comment]
Not long. The bots immediately make a build, unless they are busy with other builds.

If you go to: https://github.com/flathub/com.github.wwmm.pulseeffects/commits/master

You can see a green check mark (or some other symbol, dependent on status) next to the latest commit. From there it is easy to find all info from the build bots, live even.

In this case it seems to be done already, although in my experience it may take another few hours or at most a day until you see the update. If you want something more precise I would ask the Flathub maintainers.

**Comment by RafaelKr** [comment]
Okay, I saw that the builds were successful, but Flathub still lists 4.8.2, wasn't sure if the builds are enough or if you had to do some sort of release process besides the build.

When I try to update it says
```
...
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/1.6[/de, /en]
F: Transaction: install/update flathub:runtime/com.github.wwmm.pulseeffects.Locale/x86_64/stable[/de, /en]
F: flathub:x86_64 appstream age 74349 is less than ttl 86400
```

So maybe it's available in `(86400−74349)÷60 = 200,85 minutes` which are around 3,5 hours? So I'm just waiting now and check it then :)

Oh, I hope you slept well anyway! :)

**Pull request merged**
