### PR TITLE
(Don't merge) Add note about easyeffects

### PR DESCRIPTION
**Pull request by vchernin**
Made some maybe helpful comment so I could see if it still builds as this couldn't build locally.

### CODE REVIEW

**Comment by vchernin** [comment]
I wonder why buildbot succeeds but flatpak-builder on my local machine (Fedora 34 Silverblue toolbox) doesn't? I was under the impression that they should behave the same, but apparently here they didn't.

I'll try to take a look again at this later.

**Comment by hfiguiere** [comment]
what's the error? flatpak-builder runs on the host, not in the sandbox.

**Comment by vchernin** [comment]
Earlier I was getting this: 

`[128/507] Generating giomm-credentials.cc with a custom commandError: module glibmm: Child process exited with code 137`

Build bot's log showed `[128/507] Compiling C++ object glib/glibmm/libglibmm-2.4.so.1.3.0.p/meson-generated_.._threads.cc.o`

Now I get:

`Error: module boost: Child process exited with code 137`

I am not sure what is wrong with my system, I tried recreating the toolboxes and also install flatpak-builder on the host system. It's definitely a specific issue to my install as it built just fine in a Ubuntu 21.04 virtual machine by just installing flatpak-builder through apt as normal. It's probably some weird quirk with silverblue or something strange that I've broken.

Actually it may just be a cpu problem according to [this thread](https://www.reddit.com/r/flatpak/comments/kkjkfd/help_needed_with_flatpakbuilder_child_process/). I'll try again later.

**Comment by wwmm** [comment]
>module boost: Child process exited with code 137

We do not use boost anymore. If you have no other reason to compile it you can remove.

>glib/glibmm/libglibmm-2.4.so.1.3.0

THe glibmm for gtk4 is glibmm-2.68

**Comment by wwmm** [comment]
You can also remove gstreamer libraries from the dependencies if you did not do that yet.

**Comment by wwmm** [comment]
The pkgbuild I use on Arch Linux should give an idea of what is needed https://github.com/wwmm/easyeffects/blob/master/PKGBUILD

**Comment by vchernin** [comment]
Not needed anymore, see https://github.com/flathub/com.github.wwmm.pulseeffects/issues/44

**Pull request closed without merging**
