### PR TITLE
Update to 5.0.3

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
I tried it locally and I got it working.

image

Closes https://github.com/flathub/com.github.wwmm.pulseeffects/issues/44

/cc @vchernin

### CODE REVIEW

**Comment by lionirdeadman** [comment]
Works for me

**Comment by vchernin** [comment]
Works for me! Great work @TheEvilSkeleton!

**Comment by TheEvilSkeleton** [comment]
@wwmm in case you missed it, we got the latest version working.

**Comment by lionirdeadman** [comment]
Still works, merge?

cc: @AsavarTzeth

**Comment by TheEvilSkeleton** [comment]
Works well for me.

**Comment by hfiguiere** [comment]
Thanks!

**Pull request merged**
