### PR TITLE
EOL PulseEffects

### PR DESCRIPTION
**Pull request by Doomsdayrs**
PulseEffects is now EasyEffects, and has been replaced.

The below adds these details to the flatpak

### CODE REVIEW

**Comment by vchernin** [comment]
I don't think we want to do this. PulseEffects works on both PulseAudio and PipeWire, but EasyEffects only works on PipeWire.

Merging this means many users will switch to EasyEffects, and many will be confused when nothing works. 

PulseEffects is still maintenance mode, so it might get critical updates, eg. when a dependency makes a change that breaks it. So PulseEffects is not entirely EOL.

**Comment by Doomsdayrs** [comment]
> I don't think we want to do this. PulseEffects works on both PulseAudio and PipeWire, but EasyEffects only works on PipeWire.
> 
> Merging this means many users will switch to EasyEffects, and many will be confused when nothing works.
> 
> PulseEffects is still maintenance mode, so it might get critical updates, eg. when a dependency makes a change that breaks it. So PulseEffects is not entirely EOL.

Isn't pipewire standard for many distros now? Aside from ubuntu (they do not even have flathub support anyways).

**Comment by vchernin** [comment]
Unfortunately PipeWire for audio is not very standard yet. The only major distro that defaults to PipeWire for audio (to my knowledge) is still only Fedora. Things like Arch don't have "defaults" so they can't really be counted IMO.

EasyEffects Flatpak does have a warning dialog when running on a system potentially without PipeWire, but that doesn't help PulseEffects users, just avoids some confusion with EasyEffects.

Yes PulseAudio users could just use the PulseEffects DEB package, but I don't see a need why? This Flathub package is not abandoned or anything, it's still being watched.

**Comment by Doomsdayrs** [comment]
> Unfortunately PipeWire for audio is not very standard yet. The only major distro that defaults to PipeWire for audio (to my knowledge) is still only Fedora. Things like Arch don't have "defaults" so they can't really be counted IMO.
> 
> EasyEffects Flatpak does have a warning dialog when running on a system potentially without PipeWire, but that doesn't help PulseEffects users, just avoids some confusion with EasyEffects.
> 
> Yes PulseAudio users could just use the PulseEffects DEB/RPM/Arch etc package, but I don't see a need why? This Flathub package is not abandoned or anything, it's still being watched.

Good point, I suppose this can just be left on the drawing board until the day comes

**Comment by vchernin** [comment]
Since even Ubuntu 22.04 will likely not default to PipeWire, I will close this for now. When the day comes indeed this can be reopened.

Until then, maybe PulseEffects could be updated to suggest EasyEffects if a PipeWire audio server is detected. I'll suggest that upstream.

**Comment by kaovilai** [comment]
RHEL 8 is still not defaulting to Pipewire.

**Pull request closed without merging**
